import React, { useEffect } from "react";
import { useHeader } from '../../components/HeaderContext';


const TermsAndConditons = () => {
  const { setTitle } = useHeader();

  useEffect(() => {
    setTitle("Terms & Conditions");
  }, [setTitle]);
  
  return (
    <div className='p-3'>
      <h3>"MANDI CENTRAL APP" Terms & Conditions</h3>
      <p>Samvaay Commodity Private Limited</p>

      <h5 className='fw-bold mt-3'>What is the Mandi Central Mobile Application?</h5>
      <p>The "Mandi Central" application is owned and operated by Samvaay Commodity Private Limited, a company incorporated under the laws of India, having its registered office at Plot no. 154/1, Ward 23 Suyog SBI Colony Amalner Jalgaon, Maharashtra 425401, India. Mandi Central is an application in the Apple & Android Store that facilitates users registered on Mandi Central by providing agri-business assistance services like business leads, market data, analysis, and related services for agri-commodities.</p>
      <p>Note : Please refer google doc of the terms and condition. I have updated it there for your reference.</p>

      <h5 className='fw-bold mt-3'>Content & Report Disclaimer</h5>
      <p>By accessing the Mandi Central app, you have read, understood, and agree to be legally bound by the terms of the following disclaimer and user agreement mandi central app has taken due care and caution in the compilation of data for its mobile app and reports. Mandi Central app advises users to check with certified experts before making any trading/business/ investment decision. However, the Mandi Central app and team do not guarantee the accuracy, adequacy, or completeness of any information and are not responsible for any errors or omissions or for the results obtained from the use of such information. Mandi Central app and team especially states that it has no financial liability whatsoever to any user on account of the use of information provided on its mobile app/reports.</p>
      <p>Mandi Central app/team is not responsible for any errors, omissions or representations on any of our pages/reports or on any links on any of our pages/ reports. Mandi Central app does not endorse in any way any advertisers on our mobile pages/reports. Please verify the veracity of all information on your own before undertaking any alliance. The information on this website is updated from time to time.</p>
      <p>Mandi Central app however excludes any warranties (whether expressed or implied), as to the quality, accuracy, efficacy, completeness, performance, fitness, or any of the contents of the website, including (but not limited) to any comments, feedback and advertisements contained within the mobile app and reports. Mandi Central app makes no warranty that the contents of the mobile app/reports are free from infection by viruses or anything else that has contaminating or destructive properties and shall have no liability in respect thereof. Part of this mobile app/report contains advertising and other material submitted to us by third parties. Kindly note that those advertisers are responsible for ensuring that material submitted for inclusion on the mobile app complies with all legal requirements. Although acceptance of advertisements on the mobile app/pages is subject to our terms and conditions which are available on request, we do not accept liability in respect of any advertisements. There are risks associated with utilizing internet and short messaging system (SMS) based information and research dissemination services. Subscribers/users are advised to understand that the services can fail due to failure of hardware, software, and Internet connection. While we ensure that the messages are delivered in time to the subscriber's Mobile/internet Network, the delivery of these messages to the customer's mobile phone/handset is the responsibility of the customer's Mobile Network. SMS, notification may be delayed and/or not delivered to the customer's mobile phone/handset on certain days, owing to technical reasons that can only be addressed by the customer's Mobile/internet Network, and mandi central app and/or its employees cannot be held responsible for the same.</p>
      <p>Mandi Central hereby expressly disclaims any implied warranties imputed by the laws of any jurisdiction. We consider ourselves and intend to be subject to the jurisdiction only of the courts of Mumbai in India. If you don't agree with any of our disclaimers above please do not read the material on any of our pages/reports. This mobile app is specifically for users in the territory of India. Although access to users outside India is not denied, Mandi Central shall have no legal liabilities whatsoever in any laws of any jurisdiction other than India. We reserve the right to make changes to our mobile app and these disclaimers, terms, and conditions at any time. Commodity trading is inherently risky and you agree to assume complete and full responsibility for the outcomes of all trading decisions that you make, including but not limited to loss of capital. None of the trading calls made by the mandi central app/team should be construed as an offer to buy or sell, nor advice to do so. Under no circumstances should any person at this mobile app/report make trading decisions based solely on the information discussed herein. We are not a qualified trading/ investment/ business advisor and you should not construe any information discussed herein to constitute investment/trading/business advice. It is informational in nature. You should consult a qualified broker or other trading advisor prior to making any actual investment, business, or trading decisions. You agree to not make actual commodity trades based on comments on the mobile app, reports, etc nor on any techniques presented nor discussed in this mobile app/ reports or any other form of information presentation. All information is for educational and informational use only. You agree to consult with a registered investment, trading, business advisor, which we are not, prior to making any trading decision of any kind. Hypothetical or simulated performance results have certain inherent limitations. Unlike an actual performance record, simulated results do not represent actual trading. No representation is being made that any account will or is likely to achieve profits or losses similar to those shown.</p>
      <p>We encourage all investors, traders, businesses, etc to use the information on the mobile app/reports as a resource only to further enhance their research on commodity markets. Nothing published on this mobile app/report should be considered as investment, trading, or business advice.</p>
      <p>Mandi central team, directors, and/or their employees take no responsibility for the veracity, validity, and correctness of the expert recommendations or other information or research. Although we attempt to research thoroughly on information provided herein, there are no guarantees of accuracy. The information presented on the mobile app/reports has been gathered from various sources believed to be providing correct information.</p>
      <p>Mandi central team, directors, and/or their employees are not responsible for errors, inaccuracies if any in the content provided on the mobile app/ reports. Any Mandi central team, director and/or their owners, officers, and employees may have positions in any commodity mentioned in this mobile app/report and may from time to time add or dispose of such commodities.</p>
      <p>Mandi central team, director, employee does not represent or endorse the accuracy or reliability of any of the information, conversation, or content contained on, distributed through, or linked, downloaded or accessed from any of the services contained on this mobile app, reports (hereinafter, the "Service"), nor the quality of any products, information or other materials displayed, purchased, or obtained by you as a result of any other information or offer by or in connection with the Service.</p>
      <p>By using the Mandi Central app including any software and content contained therein, you agree that use of the Service is entirely at your own risk. Mandi Central app team and director are not a registered investment advisor, business or broker-dealer. You understand and acknowledge that there is a very high degree of risk involved in trading commodities. Past results of any trader, or business published on this mobile app/report are not indicative of future returns by that trader and are not indicative of future returns that be realized by you. Any information, opinions, advice, or offers posted by any person or entity logged in to the mandi central app or any of its associated sites, reports, or mobile app is to be construed as public conversation only.</p>
      <p>Mandi Central makes no warranties and gives no assurances regarding the truth, timeliness, reliability, or good faith of any material posted on the Mandi Central app/reports. Mandi Central app/team/directors does not warrant that trading methods or systems presented in their services or the information herein, or obtained from advertisers or members will result in profits or losses.</p>

      <h5 className='fw-bold mt-3'>Gold Membership Subscription Disclaimer:</h5>
      <p>The Gold Membership Subscriber Agreement and Terms of Use (this “Agreement or Terms”) shall govern your use & subscription of all Products including services from Mandi Central App as offered from time to time unless other terms and conditions expressly govern.</p>
      <p>You hereby agree and explicitly give your consent to activate the services. These Terms govern the Subscriber’s access to and use of the website, mobile application, or other online service where these Terms are posted (collectively, the Site or website). By clicking an Accept, Register, or similar button or icon, connecting to the Site through a third party, or by accessing, browsing, or using the Site in any manner, Subscribers agree to be bound to these Terms and our Privacy Policy, whether or not Subscriber registered with the Site. The Site reserves the right to deny access to any person who violates these Terms.</p>

      <h3>1. GENERAL TERMS OF SALE</h3>
      <p>1.1. Definitions</p>
      <p>The term “Product" refers to Products including services available from the Mandi Central app, including but not limited to Paid Subscriptions for the Subscriber.</p>
      <p>1.2. Products</p>
      <p>The Subscriber is not required to purchase anything for the use of Mandi Central Products or apps. However, if the Subscriber does not purchase or opt for a subscription or Product, his or her access to Mandi Central Products shall be limited. A Subscriber who has subscribed for the Paid Products available on the website/mobile app of Mandi Central shall have the right to access those Products which are available under the Paid Products category. Mandi Central reserves the right to modify the Product, type, and availability of any Product at any time without any prior approval or consent from the Subscriber. Only Paid Subscribers shall have access to Paid Products of Mandi Central as per the applicable subscription fee. For details about the subscription packages, including payment methods and billing cycles, please call us.</p>

      <h5 className='fw-bold mt-3'>1.3. Processing and Payment</h5>
      <p>Mandi Central shall process the Subscriber’s purchase as promptly as soon as possible. There may be a delay in the activation of the Product while payment details are verified. Mandi Central shall reserve the right to reject any order or purchase at any time. To the extent permitted by the applicable law, payments are non-refundable after 30 days of purchase and Mandi Central does not provide refunds or credits for any partial subscription period or unwatched/unused Mandi Central content.</p>
      <p>The subscription fee for Mandi Central Product and any other charges the Subscriber may incur in connection with the use of the service, such as taxes and possible transaction fees, will be charged the to Subscriber Payment Method on the specific billing date.</p>
      <p>Mandi Central may change subscription plans and the price of its service from time to time; however, any price changes or changes to your subscription plans will apply to subsequent billing cycles following notice of the change(s) to Subscriber.</p>

      <h3>2. TRIALS AND CANCELLATION</h3>
      <p>2.1. Trials</p>
      <p>2.1.1 Mandi Central subscription may start with a trial. The duration of the trial period of the subscription will be specified during sign-up and is intended to allow new subscribers and certain former Subscribers to try the service.</p>
      <p>2.1.2 Free trial eligibility is determined by Mandi Central at its sole discretion and Mandi Central may limit eligibility or duration to prevent trial abuse. Mandi Central reserves the right to revoke the trial and put the Subscriber account on hold in the event that Mandi Central determines that the Subscriber is not eligible. Mandi Central may use information such as device ID, contact number, method of payment or account email address used with an existing or recent subscription to determine eligibility. For combinations with other offers, restrictions may apply.</p>
      <p>2.1.3 Mandi Central will charge the subscription fee for the next billing cycle to the Subscriber’s Payment Method on the subsequent day at the end of the free trial period unless the Subscriber cancels his or her subscription prior to the end of the free trial period.</p>
      <p>2.1.4 The refund would be applicable only when the subscription gets canceled within the 30-day period. The payment made would be credited back in the same mode of payment as used for the subscription. For the refund to be implemented successfully, the user shall necessarily have to inform Mandi Central at least 24 Hours prior to the expiry of the trial period.</p>
      <p>2.2 Cancellation of Subscription</p>
      <p>Only future charges associated with the Subscriber’s subscription shall be canceled at the time of cancellation of the subscription and Subscriber will continue to have access to the Mandi Central service through the end of the subscription period. The cancellation will only become effective at the end of the Subscriber’s current billing period. The Products which are sold as part of a promotion to the Subscriber shall not be covered under the cancellation and refund policy. The Subscriber hereby agrees to notify Mandi Central promptly if he or she changes his or her billing and delivery addresses and email address so that Mandi Central can continue to contact the Subscriber and send any notices required hereunder. If the Subscriber fails to notify Mandi Central promptly of a change, then any notice sent by Mandi Central to the Subscriber’s old address shall be deemed sufficient notice. Changes to Product, Service or Access Mandi Central may change, suspend, or discontinue any aspect of Products at any time, including the availability of any Product or Service. Mandi Central may also limit any feature or restrict access to Subscriber to parts or all of the Product or Service without notice or liability.</p>
      
      <h5 className='fw-bold mt-3'>Device policy</h5>
      <p>The subscriber is not allowed to share his/her user credentials for use by any other reader. The Product or any content viewed/services availed through the Product are for the User’s personal and non-commercial use only and may not be shared with others. The purchase provides access to an individual only to the paid content, which can be used on a maximum of 1 device however at any given point in time the Product would be active on only one Device.</p>
      
      <h5 className='fw-bold mt-3'>Cancellations by Mandi Central </h5>
      <p>User shall not archive, reproduce, distribute, modify, display, perform, publish, license, create derivative works from, offer for sale, or use (except as explicitly authorized in these Terms of Use) content and information contained on or obtained from the Product. User shall not circumvent, remove, alter, deactivate, degrade, or thwart any of the content protections in the Product; use any robot, spider, scraper, or other automated means to access the Product; decompile, reverse engineer, or disassemble any software or other products or processes accessible through the Product; insert any code or product or manipulate the content of the Product in any way; or use any data mining, data gathering or extraction method. In addition, the User shall not upload, post, e-mail, or otherwise send or transmit any material designed to interrupt, destroy, limit, or corrupt the functionality of any computer software or hardware or telecommunications equipment associated with the Product, including any software viruses or any other computer code, files or programs. Mandi Central reserves the right to terminate, deactivate, or restrict the use of the Product with or without notice and without further obligation in the event of any violation of these Terms of Use or are engaged in illegal or fraudulent use of the Product.,.</p>
      
      <h3>3. CONTENT</h3>
      <p>The Contents of the Products are intended for Subscriber’s personal, noncommercial use only. All materials published or available (including, but not limited to text, photographs, images, illustrations, designs, audio clips, video clips, “look and feel,” metadata, data, or compilations, all also known as the "Content") are protected by copyright, and owned or controlled by Mandi Central or the party credited as the provider of the Content. Subscriber shall abide by all additional copyright notices, information, or restrictions contained in any Content accessed through the Products. Mandi Central grants Subscriber a limited, non-exclusive, non-transferable right to access</p>
      <p>the Mandi Central Product and view Mandi Central Content. Except for the foregoing, no right, title, or interest shall be transferred to Subscriber. Subscriber must not copy, reproduce, republish, upload, post, transmit, or distribute such Content in any way, including by email or other electronic means and whether directly or indirectly and Subscriber must not assist any other person to do so. Without the prior written consent of the owner, modification of the Content, use of the Content on any other website or networked computer environment, or use of the Content for any purpose other than personal, noncommercial use is a violation of the copyrights, trademarks, and other proprietary rights, and is prohibited. Any use for which the Subscriber receives any remuneration, whether in money or otherwise, is a commercial use for the purposes of this clause.</p>

      <h3>TERM AND RENEWAL</h3>
      <p>This Agreement shall remain in full force and effect while the Subscriber uses the Product offered by Mandi Central. The subscriber’s subscription will automatically be renewed until it is canceled by him or her. The Subscriber must cancel his or her subscription to avoid any subscription fee on or before the last date of the subscription.</p>
      
      <h3>DISCLAIMERS OF WARRANTIES AND LIMITATIONS ON LIABILITY.</h3>
      <p>SUBSCRIBER HEREBY AGREES THAT HIS OR HER ACCESS TO, AND USE OF, THE SERVICES, PRODUCTS, AND CONTENT, AVAILABLE IS ON AN "AS-IS", "AS AVAILABLE" BASIS AND HT SPECIFICALLY DISCLAIM ANY REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY REPRESENTATIONS OR WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.</p>
      <p>Without prejudice to the forgoing paragraph, Mandi Central does not warrant that: This Website will be constantly available or available at all; or the information on this Website is complete, true, accurate, or non-misleading.</p>
      <p>Mandi Central will not be liable to the Subscriber in any way or in relation to the Contents of, or use of, or otherwise in connection with, the Website/mobile app. Mandi Central does not warrant that this site; information, Content, materials, Products (including software), or Services included on or otherwise made available to Subscriber through the Website/mobile app; their servers; or electronic communication sent from Mandi Central are free of viruses or other harmful components. All the Contents of this Site are only for general information or use. They do not constitute advice and should not be relied upon in making (or refraining from making) any decision. The information from or through this site is provided on an "AS IS" basis, and all warranties, expressed or implied of any kind, regarding any matter pertaining to any goods, Services, or channel, including without limitation, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement are disclaimed and excluded. Certain links on the Site lead to resources located on servers maintained by third parties over whom Mandi Central has no control or connection, business or otherwise as these sites are external to Mandi Central. Subscriber hereby agrees and understands that by visiting such sites Subscriber is beyond Mandi Central’s website/app. Mandi Central therefore neither endorses nor offers</p>
      <p>any judgment or warranty and accepts no responsibility or liability for the authenticity/availability of any of the goods/Services/or for any damage, loss, or harm, direct or consequential, or any violation of local or international laws that may be incurred by your visit and/ or transaction/s on these sites.</p>
      <p>MANDI CENTRAL AND ITS AFFILIATES AND THEIR RESPECTIVE, DIRECTORS, OFFICERS, EMPLOYEES, CONTENT PROVIDERS, AND AGENTS ("THE MC PARTIES") WILL NOT BE LIABLE (JOINTLY OR SEVERALLY) TO THE SUBSCRIBER OR ANY OTHER PERSON AS A RESULT OF ACCESS OR USE OF THE PRODUCTS OR SERVICES OR CONTENT, FOR INDIRECT, CONSEQUENTIAL, SPECIAL, INCIDENTAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING, WITHOUT LIMITATION, LOST PROFITS, LOST SAVINGS AND LOST REVENUES (COLLECTIVELY, THE "EXCLUDED DAMAGES"), WHETHER OR NOT CHARACTERIZED IN NEGLIGENCE, TORT, CONTRACT, OR OTHER THEORY OF LIABILITY, EVEN IF ANY OF THE MANDI CENTRAL PARTIES HAVE BEEN ADVISED OF THE POSSIBILITY OF OR COULD HAVE FORESEEN ANY OF THE EXCLUDED DAMAGES, IRRESPECTIVE OF ANY FAILURE OF AN ESSENTIAL PURPOSE OF A LIMITED REMEDY.</p>

      <h3>COMPLIANCE WITH LAWS</h3>
      <p>The Subscriber shall comply with all the applicable laws (including without limitation Foreign Exchange Management Act, 1999 and the rules made and notifications issued there under the Exchange Control Manual as may be issued by Reserve Bank of India from time to time, Customs Act, Information and Technology Act, 2000 as amended by the Information Technology (Amendment) Act 2008,</p>
      <p>Prevention of Money Laundering Act, 2002 and the rules made there under, the Foreign Contribution Regulation Act, 1976 and the rules made there under, the Income Tax Act, 1961 and the rules made there under, the Export-Import Policy of government of India) applicable to them respectively for using Payment Facility and MANDI CENTRAL Website/App.</p>

      <h3>SUBSCRIBER ARRANGEMENT WITH BANK</h3>
      <p>All Valid Credit / Debit/ Cash Card/ and other payment instruments are processed using a Credit Card payment gateway or appropriate payment system infrastructure and the same will also be governed by the terms and conditions agreed to between the Subscriber and the respective Issuing Bank and payment instrument issuing company. All Online Bank Transfers from Valid Bank Accounts are processed using the gateway provided by the respective Issuing Bank which supports Payment Facility to provide these Services to the Subscribers. All such Online Bank Transfers on Payment Facility are also governed by the terms and conditions agreed to between the subscriber and the respective Issuing Bank.</p>
      
      <h3>INDEMNITY</h3>
      <p>Subscriber shall indemnify and hold harmless MANDI CENTRAL, its owner, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys' fees, made by any third party or penalty imposed due to or arising out of Subscriber breach of this Terms of Use, Privacy Policy, and other Policies, or violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.</p>

      <h3> APPLICABLE LAW</h3>
      <p>Terms of Use shall be governed by and interpreted and constructed in accordance with the laws of India. The place of jurisdiction shall be exclusively in MUMBAI.</p>

      <h3>CONTACT US</h3>
      <p>Please contact us for any questions or comments (including all inquiries unrelated to copyright infringement) regarding MANDI CENTRAL Products. <strong>Email: tradeforsure3@gmail.com</strong></p>

      <h3>Subscription & Disclaimer</h3>
      <p>If you choose to provide us with your e-mail address and/or other contact info (indirect) personally identifiable information, we will use such information to send you our newsletter/research content based on your usage on the website of the mandi Central mobile application or to respond to your inquiry. When you unsubscribe from our newsletter/service you will stop receiving project newsletters. Please refer to our full Privacy Policy.</p>

      <h3>Copyright</h3>
      <p>The copyright on all texts and images on the newsletter/research article / mobile application is held by the mandi central app and company only. The newsletter/ research articles, including text and images, may not be copied and distributed for any use without the prior consent of the mandi central app and company. If any use is approved by the mandi central mobile app or company, the following conditions apply in this regard:</p>
      <ul>
        <li>it should be mentioned that the mandi central mobile app is the source of the copied material;</li>
        <li>this statement of copyright should appear on all forms of distribution.</li>
      </ul>

      <h5 className='fw-bold mt-3'>E-mail</h5>
      <p>You may send us an e-mail. However, if you communicate with us by e-mail, you should note that the security of internet e-mail is uncertain. By sending sensitive or confidential e-mail messages which are not encrypted you accept the risks of such uncertainty and possible lack of confidentiality over the Internet.</p>
      
      <h5 className='fw-bold mt-3'>No warranty</h5>
      <p> The information contained in this newsletter/research content is provided to the subscribers/users to help them sell or buy the products. It does not constitute/contain any legal / business advice. Although we try to provide quality information, all information in the newsletter/ research content/ mobile application is provided "as is", with no guarantee of completeness, accuracy, timeliness, or of the results obtained from the use of this information, and without warranty of any kind, express or implied, including, but not limited to warranties of performance, merchantability, and fitness for a particular purpose.</p>

      <h5 className='fw-bold mt-3'>No liability</h5>
      <p>We do not represent that the use of the information contained in the newsletter / mobile application/research article does not infringe upon the rights of third parties. In no event will mandi central application or company or any of its project partners be liable to you or any third party for any decision made or action taken in reliance on the information in this mobile application, research content, or newsletter or for any consequential, special or similar damages, even if advised of the possibility of such damages.</p>

      <h5 className='fw-bold mt-3'>Links</h5>
      <p>Certain hyperlinks in this newsletter may connect to websites held/maintained by third parties over whom Mandi Central application or company has no control. Mandi Central application or company makes no representations as to the accuracy of the information contained in third-party websites and does not sponsor or endorse the content thereof.</p>

      <h5 className='fw-bold mt-3'>Changes</h5>
      <p>We may make changes to this information at any time without prior notice. We make no commitment to update the information contained in this mobile application/newsletter/research article . Please do not hesitate to contact us, should you have any questions in relation to the information contained in the mobile application/ research article or newsletter.</p>

      <h5 className='fw-bold mt-3'>Severability</h5>
      <p>If a section of this disclaimer is determined by any court or other competent authority to be unlawful and/or unenforceable, the other sections of this disclaimer continue in effect. If any unlawful and/or unenforceable section would be lawful or enforceable if part of it were deleted, that part will be deemed to be deleted, and the rest of the section will continue in effect.</p>

      <h5 className='fw-bold mt-3'>Law and jurisdiction</h5>
      <p>This disclaimer will be governed by and construed in accordance with the laws of Republic of India, and any disputes relating to this disclaimer will be subject to the exclusive jurisdiction of the courts of Mumbai, India.</p>

      <h5 className='fw-bold mt-3'>Our details</h5>
      <p>In this disclaimer, "we" means mandi central mobile application and company Samvaay Commodity Private Limited.</p>
    </div>
  )
}

export default TermsAndConditons
